// ─────────────────────────────────────────────
//  LLM MODEL DATA  (prices = USD per 1M tokens)
// ─────────────────────────────────────────────
const PROVIDERS = {
  openai:    { name: "OpenAI",    color: "#10a37f", logo: "🟢" },
  anthropic: { name: "Anthropic", color: "#c9784f", logo: "🟠" },
  groq:      { name: "Groq",      color: "#f55036", logo: "🔴" },
  google:    { name: "Google",    color: "#4285f4", logo: "🔵" },
  mistral:   { name: "Mistral",   color: "#7b5ea7", logo: "🟣" },
  meta:      { name: "Meta",      color: "#0866ff", logo: "🔷" },
  cohere:    { name: "Cohere",    color: "#39594d", logo: "🟤" },
};

const MODELS = [
  // ── OpenAI ──────────────────────────────────
  {
    id: "gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 128000,
    description: "Flagship multimodal model — text, vision & audio",
    speed: "Fast",
    tier: "flagship",
    features: ["Multimodal", "Vision", "Function Calling", "JSON Mode"],
  },
  {
    id: "gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o Mini",
    inputPrice: 0.15,
    outputPrice: 0.60,
    contextWindow: 128000,
    description: "Affordable, intelligent small model",
    speed: "Very Fast",
    tier: "efficient",
    features: ["Multimodal", "Vision", "Function Calling"],
  },
  {
    id: "gpt-4-turbo",
    provider: "openai",
    name: "GPT-4 Turbo",
    inputPrice: 10.00,
    outputPrice: 30.00,
    contextWindow: 128000,
    description: "High-intelligence GPT-4 with 128K context",
    speed: "Moderate",
    tier: "flagship",
    features: ["Vision", "Function Calling", "JSON Mode"],
  },
  {
    id: "gpt-3.5-turbo",
    provider: "openai",
    name: "GPT-3.5 Turbo",
    inputPrice: 0.50,
    outputPrice: 1.50,
    contextWindow: 16385,
    description: "Fast and affordable for simple tasks",
    speed: "Very Fast",
    tier: "budget",
    features: ["Function Calling", "JSON Mode"],
  },
  {
    id: "o1",
    provider: "openai",
    name: "o1",
    inputPrice: 15.00,
    outputPrice: 60.00,
    contextWindow: 200000,
    description: "Advanced reasoning model for complex tasks",
    speed: "Slow",
    tier: "reasoning",
    features: ["Reasoning", "200K Context"],
  },
  {
    id: "o1-mini",
    provider: "openai",
    name: "o1-mini",
    inputPrice: 3.00,
    outputPrice: 12.00,
    contextWindow: 128000,
    description: "Smaller, faster reasoning model",
    speed: "Moderate",
    tier: "reasoning",
    features: ["Reasoning"],
  },
  {
    id: "o3-mini",
    provider: "openai",
    name: "o3-mini",
    inputPrice: 1.10,
    outputPrice: 4.40,
    contextWindow: 200000,
    description: "Latest small reasoning model",
    speed: "Fast",
    tier: "reasoning",
    features: ["Reasoning", "200K Context"],
  },

  // ── Anthropic Claude ─────────────────────────
  {
    id: "claude-3-5-sonnet",
    provider: "anthropic",
    name: "Claude 3.5 Sonnet",
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    description: "Most intelligent Claude model, best for complex tasks",
    speed: "Fast",
    tier: "flagship",
    features: ["Vision", "200K Context", "Tool Use", "Artifacts"],
  },
  {
    id: "claude-3-5-haiku",
    provider: "anthropic",
    name: "Claude 3.5 Haiku",
    inputPrice: 0.80,
    outputPrice: 4.00,
    contextWindow: 200000,
    description: "Fast and compact — near-instant responsiveness",
    speed: "Very Fast",
    tier: "efficient",
    features: ["Vision", "200K Context", "Tool Use"],
  },
  {
    id: "claude-3-opus",
    provider: "anthropic",
    name: "Claude 3 Opus",
    inputPrice: 15.00,
    outputPrice: 75.00,
    contextWindow: 200000,
    description: "Most powerful model for demanding tasks",
    speed: "Moderate",
    tier: "flagship",
    features: ["Vision", "200K Context", "Tool Use"],
  },
  {
    id: "claude-3-haiku",
    provider: "anthropic",
    name: "Claude 3 Haiku",
    inputPrice: 0.25,
    outputPrice: 1.25,
    contextWindow: 200000,
    description: "Fastest and most affordable Claude 3",
    speed: "Very Fast",
    tier: "budget",
    features: ["Vision", "200K Context"],
  },

  // ── Groq ─────────────────────────────────────
  {
    id: "llama-3.1-70b-groq",
    provider: "groq",
    name: "Llama 3.1 70B (Groq)",
    inputPrice: 0.59,
    outputPrice: 0.79,
    contextWindow: 131072,
    description: "Meta's Llama 3.1 70B on Groq's ultra-fast LPU",
    speed: "Blazing Fast",
    tier: "efficient",
    features: ["Open Source", "Tool Use", "128K Context"],
  },
  {
    id: "llama-3.1-8b-groq",
    provider: "groq",
    name: "Llama 3.1 8B (Groq)",
    inputPrice: 0.05,
    outputPrice: 0.08,
    contextWindow: 131072,
    description: "Smallest Llama 3.1 — extremely fast & cheap",
    speed: "Blazing Fast",
    tier: "budget",
    features: ["Open Source", "128K Context"],
  },
  {
    id: "mixtral-8x7b-groq",
    provider: "groq",
    name: "Mixtral 8x7B (Groq)",
    inputPrice: 0.24,
    outputPrice: 0.24,
    contextWindow: 32768,
    description: "Mistral's MoE model at Groq speed",
    speed: "Blazing Fast",
    tier: "budget",
    features: ["Open Source", "MoE Architecture"],
  },
  {
    id: "gemma2-9b-groq",
    provider: "groq",
    name: "Gemma2 9B (Groq)",
    inputPrice: 0.20,
    outputPrice: 0.20,
    contextWindow: 8192,
    description: "Google's Gemma2 on Groq",
    speed: "Blazing Fast",
    tier: "budget",
    features: ["Open Source"],
  },
  {
    id: "llama-3.3-70b-groq",
    provider: "groq",
    name: "Llama 3.3 70B (Groq)",
    inputPrice: 0.59,
    outputPrice: 0.79,
    contextWindow: 131072,
    description: "Latest Llama 3.3 70B on Groq",
    speed: "Blazing Fast",
    tier: "efficient",
    features: ["Open Source", "Tool Use"],
  },

  // ── Google ───────────────────────────────────
  {
    id: "gemini-1.5-pro",
    provider: "google",
    name: "Gemini 1.5 Pro",
    inputPrice: 1.25,
    outputPrice: 5.00,
    contextWindow: 2000000,
    description: "1M–2M context window, multimodal powerhouse",
    speed: "Moderate",
    tier: "flagship",
    features: ["2M Context", "Multimodal", "Video", "Audio"],
  },
  {
    id: "gemini-1.5-flash",
    provider: "google",
    name: "Gemini 1.5 Flash",
    inputPrice: 0.075,
    outputPrice: 0.30,
    contextWindow: 1000000,
    description: "Fast and versatile with 1M context",
    speed: "Very Fast",
    tier: "efficient",
    features: ["1M Context", "Multimodal", "Vision"],
  },
  {
    id: "gemini-1.5-flash-8b",
    provider: "google",
    name: "Gemini 1.5 Flash-8B",
    inputPrice: 0.0375,
    outputPrice: 0.15,
    contextWindow: 1000000,
    description: "Smallest and most affordable Gemini",
    speed: "Blazing Fast",
    tier: "budget",
    features: ["1M Context", "Vision"],
  },
  {
    id: "gemini-2.0-flash",
    provider: "google",
    name: "Gemini 2.0 Flash",
    inputPrice: 0.10,
    outputPrice: 0.40,
    contextWindow: 1000000,
    description: "Next-gen speed with multimodal output",
    speed: "Blazing Fast",
    tier: "efficient",
    features: ["1M Context", "Multimodal Output", "Live API"],
  },

  // ── Mistral ──────────────────────────────────
  {
    id: "mistral-large",
    provider: "mistral",
    name: "Mistral Large",
    inputPrice: 2.00,
    outputPrice: 6.00,
    contextWindow: 131072,
    description: "Top-tier reasoning and knowledge model",
    speed: "Fast",
    tier: "flagship",
    features: ["Function Calling", "128K Context", "JSON Mode"],
  },
  {
    id: "mistral-small",
    provider: "mistral",
    name: "Mistral Small",
    inputPrice: 0.20,
    outputPrice: 0.60,
    contextWindow: 32768,
    description: "Efficient model for simple tasks",
    speed: "Very Fast",
    tier: "efficient",
    features: ["Function Calling"],
  },
  {
    id: "codestral",
    provider: "mistral",
    name: "Codestral",
    inputPrice: 0.20,
    outputPrice: 0.60,
    contextWindow: 32768,
    description: "Specialized for code generation and completion",
    speed: "Fast",
    tier: "efficient",
    features: ["Code Specialist", "Fill-in-Middle"],
  },
  {
    id: "mistral-nemo",
    provider: "mistral",
    name: "Mistral Nemo",
    inputPrice: 0.15,
    outputPrice: 0.15,
    contextWindow: 128000,
    description: "12B model with strong multilingual support",
    speed: "Very Fast",
    tier: "budget",
    features: ["Multilingual", "128K Context"],
  },

  // ── Meta (via Together/Replicate) ────────────
  {
    id: "llama-3.1-405b",
    provider: "meta",
    name: "Llama 3.1 405B",
    inputPrice: 3.00,
    outputPrice: 3.00,
    contextWindow: 131072,
    description: "Meta's largest open model, frontier-level quality",
    speed: "Moderate",
    tier: "flagship",
    features: ["Open Source", "128K Context", "Tool Use"],
  },
  {
    id: "llama-3.2-90b",
    provider: "meta",
    name: "Llama 3.2 90B",
    inputPrice: 0.90,
    outputPrice: 0.90,
    contextWindow: 131072,
    description: "Large multimodal Llama with vision",
    speed: "Fast",
    tier: "efficient",
    features: ["Open Source", "Vision", "128K Context"],
  },

  // ── Cohere ───────────────────────────────────
  {
    id: "command-r-plus",
    provider: "cohere",
    name: "Command R+",
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 128000,
    description: "Best for RAG, grounding & enterprise search",
    speed: "Fast",
    tier: "flagship",
    features: ["RAG Optimized", "128K Context", "Tool Use"],
  },
  {
    id: "command-r",
    provider: "cohere",
    name: "Command R",
    inputPrice: 0.15,
    outputPrice: 0.60,
    contextWindow: 128000,
    description: "Affordable RAG-focused model",
    speed: "Very Fast",
    tier: "efficient",
    features: ["RAG Optimized", "128K Context"],
  },
];

// Preset usage scenarios
const PRESETS = {
  chatbot: {
    label: "💬 Chatbot",
    inputTokens: 500,
    outputTokens: 300,
    requestsPerDay: 500,
    days: 30,
  },
  summarizer: {
    label: "📄 Summarizer",
    inputTokens: 5000,
    outputTokens: 500,
    requestsPerDay: 200,
    days: 30,
  },
  codeAssist: {
    label: "💻 Code Assistant",
    inputTokens: 3000,
    outputTokens: 1500,
    requestsPerDay: 150,
    days: 30,
  },
  enterprise: {
    label: "🏢 Enterprise",
    inputTokens: 20000,
    outputTokens: 5000,
    requestsPerDay: 1000,
    days: 30,
  },
};
